# Generated by Django 3.2.10 on 2024-02-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_password2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Men', models.CharField(max_length=100)),
                ('Women', models.CharField(max_length=100)),
                ('kid', models.CharField(max_length=100)),
            ],
        ),
    ]
