# Generated by Django 3.2.10 on 2024-02-02 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Men',
            new_name='Category_Name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Women',
        ),
        migrations.RemoveField(
            model_name='category',
            name='kid',
        ),
    ]
