# Generated by Django 3.2.10 on 2024-02-05 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20240205_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='otp_secret_key',
            new_name='otp',
        ),
    ]
