# Generated by Django 3.2.10 on 2024-02-08 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_details',
        ),
    ]
