# Generated by Django 3.2.10 on 2024-02-08 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_user_detail_profile_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_detail',
            new_name='userdetail',
        ),
    ]
