# Generated by Django 3.2.10 on 2024-02-08 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_rename_user_detail_userdetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userdetail',
            new_name='user_details',
        ),
    ]
