# Generated by Django 3.2.10 on 2024-02-08 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='user',
        ),
    ]
