# Generated by Django 3.2.10 on 2024-02-08 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_remove_userdetails_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sample',
        ),
    ]
