# Generated by Django 3.2.10 on 2024-02-12 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_delete_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow')], default='red', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xl', 'XL')], default='medium', max_length=10),
        ),
    ]
