# Generated by Django 3.2.10 on 2024-02-12 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='id',
            new_name='product_id',
        ),
    ]
